## 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [33]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Intro to Tensors

### Creating Tensors

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get item from tensor back as a python type (like an int)
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[85,8],[9,10]])
MATRIX

tensor([[85,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3], [3,5,6], [4,2,3]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 6],
         [4, 2, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [4, 2, 3]])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with random numbers and then adjust them to better represent the data.

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=rand#torch.rand

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1061, 0.5720, 0.7584, 0.3154],
        [0.6978, 0.9764, 0.1822, 0.5675],
        [0.5175, 0.6872, 0.5136, 0.6789]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Creating a random tensor with a similar shape as an image
random_image_tensor = torch.rand(size=(255,255,3)) # the arguements are [height, width, color_channels] (RGB)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([255, 255, 3]), 3)

In [ ]:
# Creating a tensor of all zeros 
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Creating a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Default data type of a tensor
ones.dtype

torch.float32

### Creating tensors using a certain range & tensors-like

`torch.arange` - https://pytorch.org/docs/stable/generated/torch.arange.html?highlight=arange#torch.arange

like tensors - https://pytorch.org/docs/stable/generated/torch.zeros_like.html

In [31]:
# Creating a tensor with range of 1 to 10
one_to_ten = torch.arange(0,11) 
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# Creating tensors like - create a tensor with the same shape as another
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Data Types & Parameters

Data Types - https://pytorch.org/docs/stable/tensors.html

This matters because of precision - https://en.wikipedia.org/wiki/Precision_(computer_science)

Issues you can run into using pytorch: 
1. Tensors might not be the right data type
2. Tensors might not be the right shape
3. Tensors might not be on the right device

In [40]:
# Float 32 Tensor
float_32_tensor = torch.tensor([4.0, 2.0, 0.0], dtype=None)
float_32_tensor

tensor([4., 2., 0.])

In [41]:
float_32_tensor.dtype

torch.float32

In [42]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([4., 2., 0.], dtype=torch.float16)

In [51]:
# Getting Tensor Info (attributes)

tensor = torch.tensor([4.0, 2.0, 0.0], 
                               dtype=None, # data type of tensor (usually either 32 or 16 float)
                               device=None, # either on cpu or gpu i.e. cuda, (cannot compute tensors on different devices)
                               requires_grad=False) # whether or not you want to track gradients with this tensors operations

print(tensor)
print(f"Tensor Data Type: {tensor.dtype}")
print(f"Tensor Shape: {tensor.shape}")
print(f"Tensor Device: {tensor.device}")

tensor([4., 2., 0.])
Tensor Data Type: torch.float32
Tensor Shape: torch.Size([3])
Tensor Device: cpu


### Tensor Manipulation & Operations

Operations:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication (x)